use utoipa::OpenApi;

// For some reason it wants the full qualified paths with the "__" prefix as shown.
use crate::api_messages;
use crate::conversation;
use crate::conversation::__path_create_conversation;
use crate::conversation::__path_delete_conversation;
use crate::conversation::__path_get_conversation;
use crate::login;
use crate::login::__path_login_request;
use crate::register;
use crate::register::__path_register_request;
use crate::user;
use crate::user::__path_user_by_id;

/// This module is for utoipa's autogenerated OpenAPI documentation.

#[derive(OpenApi)]
#[openapi(
    paths(
        login_request,
        register_request,
        user_by_id,
        create_conversation,
        get_conversation,
        delete_conversation,
    ),
    components(
        schemas(
            login::LoginInformation,
            api_messages::GenericResponse,
            register::RegisterInformation,
            register::RegisterResponse,
            user::User,
            conversation::Conversation,
            conversation::CreateConversationRequest,
            conversation::CreateConversationResponse,
        )
    ),
    tags(
        (name = "cogito_api", description = "Cogito API endpoints.")
    ),
    info(
        title = "Cogito API",
        version = "1.0",
        description = "API backend for the Cogito project.",
        license(
            name = "PolyForm Noncommercial License 1.0.0",
            url = "https://polyformproject.org/licenses/noncommercial/1.0.0/"
        ),
        contact(
            name = "Lucas Marta",
            url = "https://lucasmarta.com",
            email = "lucas.marta0799@gmail.com"
        ),
    )
)]
pub struct ApiDoc;
